Repository Ayu-hack/Portfolio, pull requests merged in 2024-10, with the labels that each got.

#2 CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement, good first issue

#3 add contact-us feature
  index.html
  styles.css
Labels: hacktoberfest-accepted

#6 Updated changes after PR merge
  SimplePortfolio/index.html
  SimplePortfolio/project1.html
  SimplePortfolio/project2.html
  SimplePortfolio/script.js
  SimplePortfolio/styles.css
Labels: enhancement, hacktoberfest-accepted

#9 Added new features
  index.html
  profile_pic.avif
  script.js
  styles.css
Labels: good first issue, hacktoberfest-accepted
